name: Run test case

on: [push, pull_request]

jobs:
    run_test_case:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/emqx/emqx-builder/5.3-9:1.15.7-26.2.5-3-ubuntu22.04

        steps:
        - uses: actions/checkout@v4.2.2

        - name: Compile
          run: |
            make dialyzer

        - name: Test
          run: |
            make test

        - uses: actions/upload-artifact@v4.6.2
          if: always()
          with:
            name: logs
            path: _build/test/logs
